back/config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  devise_for :users

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
end

back/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

back/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  

  validates :content, presence: true
  validates :user, presence: true
end

back/app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :title, :content, presence: true

    has_many :comments, dependent: :destroy
end

back/app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

back/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  allow_browser versions: :modern
end

back/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post
    before_action :set_comment, only: [:edit, :update, :destroy]
    before_action :authorize_user!, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  
    def create
        @comment = @post.comments.build(comment_params)
        @comment.user = current_user
      
        if @comment.save
          respond_to do |format|
            format.html { redirect_to @post, notice: "Comentário adicionado com sucesso." }
            format.turbo_stream
          end
        else
          flash[:alert] = "Erro ao adicionar comentário. Verifique o conteúdo."
          respond_to do |format|
            format.html { redirect_to @post }
            format.turbo_stream
          end
        end
    end
  
    def edit; end
  
    def update
      if @comment.update(comment_params)
        respond_to do |format|
          format.html { redirect_to @post, notice: "Comentário atualizado com sucesso." }
          format.turbo_stream
        end
      else
        respond_to do |format|
          format.html { render :edit, status: :unprocessable_entity }
          format.turbo_stream
        end
      end
    end
  
    def destroy
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to @post, notice: "Comentário excluído com sucesso." }
        format.turbo_stream
      end
    end
  
    private
  
    def set_post
      @post = Post.find(params[:post_id])
    end
  
    def set_comment
      @comment = @post.comments.find(params[:id])
    end
  
    def comment_params
      params.require(:comment).permit(:content)
    end
  
    def authorize_user!
      redirect_to @post, alert: "Você não tem permissão para isso." unless @comment.user == current_user
    end
  end
  

back/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_post_owner, only: %i[edit update destroy]


def index
    @posts = Post.all
end

def show
  @post = Post.find(params[:id])
  @comment = @post.comments.build 
end

def new
    @post = Post.new
end

def edit
  #  @post = Post.find(params[:id])
end

def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: "Post criado com sucesso!"
    else
      render :new
    end
end

def update
    if @post.update(post_params)
      redirect_to @post, notice: "Postagem atualizada com sucesso!"
    else
      render :edit
    end
end

def destroy
    @post.destroy
    redirect_to posts_url, notice: "Postagem deletada com sucesso!"
end

  private
    
def set_post
    @post = Post.find(params[:id])
end

def authorize_post_owner
    unless @post.user == current_user
      redirect_to posts_url, alert: "Você não tem permissão para realizar esta ação."
    end
end
    
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

back/app/helpers/application_helper.rb
module ApplicationHelper
end

back/app/helpers/comments_helper.rb
module CommentsHelper
end

back/app/helpers/posts_helper.rb
module PostsHelper
end

back/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

back/app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <p><strong><%= comment.user.email %>:</strong> <%= comment.content %></p>

  <% if comment.user == current_user %>
    <%= link_to "Editar", edit_post_comment_path(comment.post, comment) %> |
    <%= button_to "Deletar", post_comment_path(comment.post, comment), method: :delete, data: { turbo_confirm: "Tem certeza?" } %>
  <% end %>
</div>

back/app/views/comments/_form.html.erb
<%= form_with model: [post, comment], local: true do |form| %>
    <div>
      <%= form.label :content, "Seu Comentário" %>
      <%= form.text_area :content, placeholder: "Digite aqui..." %>
    </div>
    <div>
      <%= form.submit "Comentar", class: "btn" %>
    </div>
  <% end %>
  

back/app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments" do %>
    <%= render @comment %>
<% end %>
  

back/app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment) %>

back/app/views/comments/edit.html.erb
<h2>Editar Comentário</h2>

<%= form_with(model: [@post, @comment], local: false) do |form| %>
  <div>
    <%= form.label :content, "Editar Comentário" %>
    <%= form.text_area :content %>
  </div>
  <%= form.submit "Atualizar Comentário" %>
<% end %>

back/app/views/comments/update.turbo_stream.erb
<%= turbo_stream.replace "comments" do %>
    <%= render @comment.post.comments %>
<% end %>
  

back/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

back/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog Umanni" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <nav aria-label="Main Navigation">
      <%= link_to "Home", root_path, class: "btn btn-primary" %>
      <% if user_signed_in? %>
        <%= link_to "Nova Postagem", new_post_path, class: "btn btn-secondary" %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger", data: { confirm: "Você tem certeza?" } %>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "btn btn-secondary" %>
      <% end %>
    </nav>
    
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

    <footer>
      <p>Teste Felipe Umanni &copy; 2024</p>
    </footer>
  </body>
</html>

back/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, "Title", style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, "Content", style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

back/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Título:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= post.content %>
  </p>

</div>

back/app/views/posts/edit.html.erb
<% content_for :title, "Editando o Post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Mostrar o post", @post %> |
  <%= link_to "Voltar para os posts", posts_path %>
</div>

back/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Postagens" %>

<h1>Postagens</h1>

<div id="posts">
  <% @posts.each do |post| %>
      <div class="post">
        <%= render post %>
        <p>
          <%= link_to "Mais sobre o post", post, class: "btn btn-primary" %>
        </p>
      </div>
    <% end %>
</div>

<p>
  <%= link_to "Criar Postagem", new_post_path, class: "btn btn-secondary" %>
</p>

back/app/views/posts/new.html.erb
<% content_for :title, "Nova Postagem" %>

<h1>Novo post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Voltar para os posts", posts_path %>
</div>

back/app/views/posts/show.html.erb
<p class="notice"><%= notice %></p>

<%= render @post %>

<div class="post-actions">
  <%= link_to "Editar Post", edit_post_path(@post), class: "btn btn-primary" %>
  <%= link_to "Voltar para os posts", posts_path, class: "btn btn-secondary" %>
  <%= button_to "Deletar Post", @post, method: :delete, class: "btn btn-danger", data: { confirm: "Você tem certeza?" } %>
</div>

<div class="comments-section">
  <h2>Comentários</h2>
  <% if @post.comments.any? %>
    <div class="comments-list">
      <% @post.comments.where.not(id: nil).each do |comment| %>
        <div class="comment">
          <p>
            <strong>
              <%= comment.user&.email || "Usuário não identificado" %>:
            </strong>
            <%= comment.content %>
          </p>
          <% if comment.user == current_user %>
            <div class="comment-actions">
              <%= link_to "Editar", edit_post_comment_path(@post, comment), class: "edit-btn" %> |
              <%= link_to "Excluir", post_comment_path(@post, comment), method: :delete, class: "delete-btn", data: { confirm: "Você tem certeza?" } %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <p class="no-comments">Nenhum comentário ainda. Seja o primeiro a comentar!</p>
  <% end %>
</div>

<div class="comment-form">
  <h3>Adicionar um Comentário</h3>
  <%= render 'comments/form', post: @post, comment: @comment %>
</div>